%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
  k1: 0.0e-01
  k2: 0.0e-02
  p1: 0.0e-06
  p2: 0.0e-05
projection_parameters:
  fx: 6.4e+02
  fy: 6.4e+02
  cx: 6.4e+02
  cy: 3.6e+02
